vectorizer:
  vector_size: 16384
  sg: 0
  min_count: 2

model:
  use_pretrain: 0
  pretrain: "vinai/phobert-base"
  batch_size: 256
  dropout: 0.5
  epochs: 50
  learning_rate: 0.001
  hidden_size: 256